version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app/src
    command: ["python", "web_interface/backend/api.py"]
    restart: unless-stopped