name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: pytest tests/ -v
    
    - name: Test web interface
      run: |
        timeout 30 streamlit run web_app.py --server.headless true &
        sleep 10
        curl -f http://localhost:8501 || exit 1

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t ddi-predictor .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8501:8501 --name test-container ddi-predictor
        sleep 15
        curl -f http://localhost:8501 || exit 1
        docker stop test-container